config/routes.rb
Rails.application.routes.draw do
  get 'cats/index'

  get 'cats/show'

  root 'cats#index'

  resources :cats, only: [:index, :show, :update]

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all 
  end

  def show
    @cat = Cat.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.clicks = @cat.clicks + 1
    @cat.save!
    respond_to do |format|
      format.html { redirect_to @cat }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<h1><%= cat.name %></h1>
<%= form_for cat, :html => { id: 'clicker', :data => {'post-url' => cat_url(cat)} } do |f| %>
  <%= image_submit_tag cat.image.url, id: 'cat' %>
<% end %>
<div>
  <span id="clicks" data-get-url="<%= cat_path(cat) %>">Clicks: </span><span id="number"><%= cat.clicks %></span>
</div>

app/views/cats/index.html.erb
<div id="column">
<% @cats.each do |cat| %>
  <%= link_to cat, remote: true, class: 'cat' do %>
    <%= image_tag cat.image.url %>
    <%= cat.name.titleize %>
  <% end %>
<% end %>
</div>
<div id="main">
</div>

app/views/cats/show.html.erb
<%= render partial: 'cat', object: @cat %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatClick</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>